# -*- coding: utf-8 -*-
"""PyBH.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UUnyL-RYEH0zdGbIIN5SqAyzwm0njQWe

# EDA with Seaborn
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# %matplotlib inline
import seaborn as sns

df= pd.read_csv('/content/BostonHousing.csv')
df
!pip install sweetviz

import sweetviz as sv

#analyzing the dataset
bhreport = sv.analyze(df)

#display the report
bhreport.show_html('Boston Housing Dataset.html')

bhreport.show_notebook()

bhreport = sv.compare(df[100:], df[:100])
# bhreport.show_html('BostonH.html')

bhreport.show_notebook()
